version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - WEBSITES_PORT=5000  # Added for Azure
      - WEBSITES_CONTAINER_START_TIME_LIMIT=1800  # Added for Azure
      - DATABASE_URL_DOCKER=${DATABASE_URL_DOCKER}
    healthcheck:  # Added health check
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: flask_bids
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # Added health check
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata: