"""Initial migration

Revision ID: f1a9169f7ca9
Revises: 
Create Date: 2024-06-19 14:03:54.213430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a9169f7ca9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factor_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labor_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factor_code', schema=None) as batch_op:
        batch_op.drop_column('labor_hours')

    # ### end Alembic commands ###
