"""Add Proposals Part 2

Revision ID: 025008a0ffff
Revises: 32f7a93503e1
Create Date: 2024-09-06 08:07:42.347802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025008a0ffff'
down_revision = '32f7a93503e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['bid_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
