"""Add revision_number to Proposal model

Revision ID: 03df53b042fa
Revises: 025008a0ffff
Create Date: 2024-09-16 11:51:55.215605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03df53b042fa'
down_revision = '025008a0ffff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
