"""removing phase

Revision ID: 312ffe1b42ce
Revises: 60268bd7455c
Create Date: 2024-08-27 00:40:06.082793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312ffe1b42ce'
down_revision = '60268bd7455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('phase')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
