"""Description of your changes
Revision ID: 3195caa7a2e4
Revises: 39112c91cd51
Create Date: 2024-09-25 16:40:46.951891
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3195caa7a2e4'
down_revision = '39112c91cd51'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in the correct order to avoid dependency issues
    op.drop_table('phase_lines')
    op.drop_table('section_lines')
    op.drop_table('proposal_phases')
    op.drop_table('proposal_sections')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate tables in the reverse order
    op.create_table('proposal_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name='proposal_sections_proposal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='proposal_sections_pkey')
    )
    
    op.create_table('proposal_phases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name='proposal_phases_proposal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='proposal_phases_pkey')
    )
    
    op.create_table('section_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['proposal_sections.id'], name='section_lines_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='section_lines_pkey')
    )
    
    op.create_table('phase_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['proposal_phases.id'], name='phase_lines_phase_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phase_lines_pkey')
    )
    # ### end Alembic commands ###