"""Add Budget Totals

Revision ID: 32f7a93503e1
Revises: 83e805103440
Create Date: 2024-09-05 19:55:46.958837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f7a93503e1'
down_revision = '83e805103440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landscaping_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('drains_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('irrigation_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('total_budget')
        batch_op.drop_column('maintenance_total')
        batch_op.drop_column('irrigation_total')
        batch_op.drop_column('drains_total')
        batch_op.drop_column('landscaping_total')

    # ### end Alembic commands ###
