"""Add revision_number to Proposal model

Revision ID: 39112c91cd51
Revises: 03df53b042fa
Create Date: 2024-09-16 12:34:16.219691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39112c91cd51'
down_revision = '03df53b042fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('revision_number')

    # ### end Alembic commands ###
