"""add poc to projects

Revision ID: 60083bfb9322
Revises: 6339cce47163
Create Date: 2024-08-26 09:22:25.278143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60083bfb9322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engineers')
    op.drop_table('architects')
    op.drop_table('vendors')
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('engineer_name')
        batch_op.drop_column('phase')
        batch_op.drop_column('architect_name')
        batch_op.drop_column('point_of_contact')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_of_contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('architect_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('engineer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey')
    )
    op.create_table('architects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='architects_pkey')
    )
    op.create_table('engineers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='engineers_pkey')
    )
    # ### end Alembic commands ###
