"""Update

Revision ID: 60268bd7455c
Revises: 8ea6da59c552
Create Date: 2024-08-26 23:15:47.730247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60268bd7455c'
down_revision = '8ea6da59c552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engineer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('architect_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('point_of_contact', sa.String(length=255), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('contact_phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('point_of_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('point_of_contact')
        batch_op.drop_column('architect_name')
        batch_op.drop_column('engineer_name')

    # ### end Alembic commands ###
