"""add basic phases
Revision ID: cf2a8ecf8ee8
Revises: 312ffe1b42ce
Create Date: 2024-08-28 23:17:58.244079
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cf2a8ecf8ee8'
down_revision = '312ffe1b42ce'
branch_labels = None
depends_on = None

def upgrade():
    # Step 1: Add the new column as nullable
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(), nullable=True))
    
    # Step 2: Set a default value for existing rows
    op.execute("UPDATE bid SET phase = 'Default' WHERE phase IS NULL")
    
    # Step 3: Alter the column to be non-nullable
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.alter_column('phase', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('phase')
    # ### end Alembic commands ###